////Re-orient joints: XYZ

global proc jointOri_xyz() {

    //Query selection
    
    string $selJoint[] = `ls -sl`;
    
    //Check size of selection
    
    if (size($selJoint) != 2){warning "Must select 2 joints";} 
    
    else if (size($selJoint) == 2){
    
        // Zero out Rotation and Joint Orient attributes of target joint to orient it to the world
        
        setAttr ($selJoint[1] + ".rx") 0;
        
        setAttr ($selJoint[1] + ".ry") 0;
        
        setAttr ($selJoint[1] + ".rz") 0;
        
        setAttr ($selJoint[1] + ".jointOrientX") 0;
        
        setAttr ($selJoint[1] + ".jointOrientX") 0;
        
        setAttr ($selJoint[1] + ".jointOrientX") 0;
        
        //Create Aim Constraint
        
        string $aimJoint[] = `aimConstraint -offset 0 0 0 -weight 1 -aimVector 1 0 0 -upVector 0 1 0 -worldUpType "vector" -worldUpVector 0 1 0 $selJoint[0] $selJoint[1]`;
        
        //Find and delete constraint
        
        string $findAimCns[] = `listRelatives -type aimConstraint $selJoint[1]`;
        
        select $findAimCns[0]; doDelete;
        
        ////Swap Rotate values of joint with Joint Orient values
        
        //Find the Rotate values of the target joint
        
        float $selJnt_rx = `getAttr ($selJoint[1] + ".rx")`;
        
        float $selJnt_ry = `getAttr ($selJoint[1] + ".ry")`;
        
        float $selJnt_rz = `getAttr ($selJoint[1] + ".rz")`;
        
        //Copy the Rotate values of the target joint to its Joint Orient attributes
        
        setAttr ($selJoint[1] + ".jointOrientX") ($selJnt_rx);
        
        setAttr ($selJoint[1] + ".jointOrientY") ($selJnt_ry);
        
        setAttr ($selJoint[1] + ".jointOrientZ") ($selJnt_rz);
        
        //To finish, zero out the Rotate values of the target joint
        
        setAttr ($selJoint[1] + ".rx") 0;
        
        setAttr ($selJoint[1] + ".ry") 0;
        
        setAttr ($selJoint[1] + ".rz") 0;
    
    }
}

////Create a joint at the center of selected vertices

//Convert selection to vertices

global proc worldJoint(){


ConvertSelectionToVertices;hilite;	selectType -ocm -alc false;selectType -ocm -polymeshVertex true;

//Find selection of componenets
string $selVert[] = `ls -sl -fl`;
    
    //Create a cluster
    string $cl[] = `newCluster " -relative -envelope 1"`;
    //Create a world joint
    select -cl;
    string $jnt = `joint`;
    //Point Constraint the joint to the cluster
    string $ptCnsJnt[] = `pointConstraint $cl $jnt`;
    //Find the Point Constraint
    string $findPtCns[] = `listRelatives -type pointConstraint $jnt`;
    //Select and delete the Point Constrain and cluster
    select $findPtCns[0] $cl[0]; doDelete;
    //Select the joint
    select -cl; select $jnt;
    }
    
////ZJT - Clean up joint rotation channels

//Query selection...
global proc jointZJT(){

string $selJnt[] = `ls -sl`;
//Find selection's Aim constraint...
string $findAim[] = `listRelatives -type aimConstraint $selJnt[0]`;
//Select and delete Aim constraint...
select $findAim; doDelete;
//Find selection's (joint) Rotate values...
float $get_jRot_x = `getAttr (($selJnt[0]) + ".rx")`;
float $get_jRot_y = `getAttr (($selJnt[0]) + ".ry")`;
float $get_jRot_z = `getAttr (($selJnt[0]) + ".rz")`;
//Set joint's "Joint Orient" values to its Rotate values...
setAttr (($selJnt[0]) + ".jointOrientX") $get_jRot_x;
setAttr (($selJnt[0]) + ".jointOrientY") $get_jRot_y;
setAttr (($selJnt[0]) + ".jointOrientZ") $get_jRot_z;
//Set joint's Rotate values to zero
setAttr (($selJnt[0]) + ".rx") 0;
setAttr (($selJnt[0]) + ".ry") 0;
setAttr (($selJnt[0]) + ".rz") 0;
}

////The Joint Orient XYZ window

//Generate only one window

//Declare "$jntOriXYZ_win"...

global proc pjge(){
    
    source "Z:/Workflow/Barbarian_1.0/scripts/Rig/增加骨骼段数大法.mel";    
    
}


global proc qxge(){
    
    source "Z:/Workflow/Barbarian_1.0/scripts/Rig/曲线创建骨骼2.mel";

    
}

string $jntOriXYZ_win;

if (`window -exists $jntOriXYZ_win`) {
    deleteUI -window $jntOriXYZ_win;
}

//Create window

string $jntOriXYZ_win = `window -widthHeight 250 185 -t "嘢人骨骼工具"`;

    columnLayout -adj 1;
    
 
    
    //Create a line to divide Instructions and Buttons
    
    separator;
    
    //Buttons
     button  -l "创建中心骨骼" -c "worldJoint" -h 30;
    
     button  -l "修正骨骼轴向" -c "jointOri_xyz" -h 30;
     
     button  -l "自动恢复骨骼默认轴向" -c "jointZJT" -h 30;
     
     button  -l "曲线创建骨骼" -c "qxge" -h 30;
      
     button  -l "平均添加骨骼" -c "pjge" -h 30;
    
    button  -l "退出" -c "deleteUI -window $jntOriXYZ_win" -h 30;



//Show window


showWindow $jntOriXYZ_win;