global proc DaiLi(){
    
    string $sels[] = `ls -sl`;
    string $LR[] = `listRelatives -shapes $sels`;

    
    for ($selv in $LR){
        
        setAttr ($selv + ".overrideEnabled") 1;
        setAttr ($selv + ".overrideLevelOfDetail") 1;
        
    }
    
}

global proc FuYuan(){
    
    string $sels[] = `ls -sl`;
    string $LR[] = `listRelatives -shapes $sels`;

    
    for ($selv in $LR){
        
        setAttr ($selv + ".overrideLevelOfDetail") 0; 
        setAttr ($selv + ".overrideEnabled") 0;
        
    }
    
}
   
//窗口界面
if (`window -ex tmWin`){
    
    deleteUI tmWin;}

window -t "模型代理工具" -wh 300 70 tmWin ;
columnLayout -adj true;

text -l "选择需要代理的模型\n点击按钮执行\n";

button -l "模型代理"  -w 10 -h 28 -c "DaiLi";

text -l "" -h 5;

button -l "复原" -w 10 -h 28 -c "FuYuan";

window -e -wh 250 100 tmWin;
showWindow tmWin;

