# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/workspace/PutaoTools/commons/ui/CGTW.ui'
#
# Created: Mon Oct 23 15:27:55 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from barbarian.utils import ui, config

class Ui_CGTWWin(ui.QtUI):
    def setupUi(self, CGTWWin):
        CGTWWin.setObjectName("CGTWWin")
        CGTWWin.resize(640, 480)
        CGTWWin.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtGui.QWidget(CGTWWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.CGTWCBProject = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGTWCBProject.sizePolicy().hasHeightForWidth())
        self.CGTWCBProject.setSizePolicy(sizePolicy)
        self.CGTWCBProject.setMinimumSize(QtCore.QSize(85, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.CGTWCBProject.setFont(font)
        self.CGTWCBProject.setObjectName("CGTWCBProject")
        self.horizontalLayout.addWidget(self.CGTWCBProject)
        self.CGTWLBLUser = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGTWLBLUser.sizePolicy().hasHeightForWidth())
        self.CGTWLBLUser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.CGTWLBLUser.setFont(font)
        self.CGTWLBLUser.setText("")
        self.CGTWLBLUser.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CGTWLBLUser.setObjectName("CGTWLBLUser")
        self.horizontalLayout.addWidget(self.CGTWLBLUser)
        self.CGTWLEUsername = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGTWLEUsername.sizePolicy().hasHeightForWidth())
        self.CGTWLEUsername.setSizePolicy(sizePolicy)
        self.CGTWLEUsername.setMinimumSize(QtCore.QSize(100, 30))
        self.CGTWLEUsername.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CGTWLEUsername.setAlignment(QtCore.Qt.AlignCenter)
        self.CGTWLEUsername.setObjectName("CGTWLEUsername")
        self.horizontalLayout.addWidget(self.CGTWLEUsername)
        self.CGTWLEPassword = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGTWLEPassword.sizePolicy().hasHeightForWidth())
        self.CGTWLEPassword.setSizePolicy(sizePolicy)
        self.CGTWLEPassword.setMinimumSize(QtCore.QSize(100, 30))
        self.CGTWLEPassword.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CGTWLEPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.CGTWLEPassword.setObjectName("CGTWLEPassword")
        self.horizontalLayout.addWidget(self.CGTWLEPassword)
        self.CGTWBtnConnect = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGTWBtnConnect.sizePolicy().hasHeightForWidth())
        self.CGTWBtnConnect.setSizePolicy(sizePolicy)
        self.CGTWBtnConnect.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.CGTWBtnConnect.setFont(font)
        self.CGTWBtnConnect.setObjectName("CGTWBtnConnect")
        self.horizontalLayout.addWidget(self.CGTWBtnConnect)
        self.CGTWLEDeregister = QtGui.QPushButton(self.centralwidget)
        self.CGTWLEDeregister.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.CGTWLEDeregister.setFont(font)
        self.CGTWLEDeregister.setObjectName("CGTWLEDeregister")
        self.horizontalLayout.addWidget(self.CGTWLEDeregister)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.CGTWTWTask = QtGui.QTreeWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.CGTWTWTask.setFont(font)
        self.CGTWTWTask.setObjectName("CGTWTWTask")
        self.verticalLayout.addWidget(self.CGTWTWTask)
        self.CGTWTEInfo = QtGui.QTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CGTWTEInfo.sizePolicy().hasHeightForWidth())
        self.CGTWTEInfo.setSizePolicy(sizePolicy)
        self.CGTWTEInfo.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.CGTWTEInfo.setFont(font)
        self.CGTWTEInfo.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.CGTWTEInfo.setReadOnly(True)
        self.CGTWTEInfo.setObjectName("CGTWTEInfo")
        self.verticalLayout.addWidget(self.CGTWTEInfo)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.CGTWPyblish = QtGui.QWidget(self.centralwidget)
        self.CGTWPyblish.setObjectName("CGTWPyblish")
        self.horizontalLayout_2.addWidget(self.CGTWPyblish)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(1, 1)
        CGTWWin.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(CGTWWin)
        self.statusbar.setObjectName("statusbar")
        CGTWWin.setStatusBar(self.statusbar)

        self.retranslateUi(CGTWWin)
        QtCore.QMetaObject.connectSlotsByName(CGTWWin)

    def retranslateUi(self, CGTWWin):
        CGTWWin.setWindowTitle(QtGui.QApplication.translate("CGTWWin", "Teamwork", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CGTWWin", "项目：", None, QtGui.QApplication.UnicodeUTF8))
        self.CGTWBtnConnect.setText(QtGui.QApplication.translate("CGTWWin", "连接", None, QtGui.QApplication.UnicodeUTF8))
        self.CGTWLEDeregister.setText(QtGui.QApplication.translate("CGTWWin", "注销", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CGTWWin", "我的任务", None, QtGui.QApplication.UnicodeUTF8))

