# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/workspace/PutaoTools/commons/ui/playblastOption.ui'
#
# Created: Tue Sep 26 16:48:44 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from barbarian.utils import ui, config

class Ui_playblastOptionDialog(ui.QtUI):
    def setupUi(self, playblastOptionDialog):
        playblastOptionDialog.setObjectName("playblastOptionDialog")
        playblastOptionDialog.resize(300, 179)
        playblastOptionDialog.setMinimumSize(QtCore.QSize(300, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(config.getPath(config.kIcon, "logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        playblastOptionDialog.setWindowIcon(icon)
        
        self.centralwidget = QtGui.QWidget(playblastOptionDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.playblastOptionNameInput = QtGui.QLineEdit(self.centralwidget)
        self.playblastOptionNameInput.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.playblastOptionNameInput.setFont(font)
        self.playblastOptionNameInput.setMaxLength(20)
        self.playblastOptionNameInput.setObjectName("playblastOptionNameInput")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.playblastOptionNameInput)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.playblastOptionCBDefault = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playblastOptionCBDefault.sizePolicy().hasHeightForWidth())
        self.playblastOptionCBDefault.setSizePolicy(sizePolicy)
        self.playblastOptionCBDefault.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.playblastOptionCBDefault.setFont(font)
        self.playblastOptionCBDefault.setObjectName("playblastOptionCBDefault")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.playblastOptionCBDefault)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.line_2)
        self.playblastOptionCBHUD = QtGui.QCheckBox(self.centralwidget)
        self.playblastOptionCBHUD.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.playblastOptionCBHUD.setFont(font)
        self.playblastOptionCBHUD.setObjectName("playblastOptionCBHUD")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.playblastOptionCBHUD)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setMinimumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playblastOptionBtnGo = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playblastOptionBtnGo.sizePolicy().hasHeightForWidth())
        self.playblastOptionBtnGo.setSizePolicy(sizePolicy)
        self.playblastOptionBtnGo.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.playblastOptionBtnGo.setFont(font)
        self.playblastOptionBtnGo.setObjectName("playblastOptionBtnGo")
        self.horizontalLayout.addWidget(self.playblastOptionBtnGo)
        self.playblastOptionBtnApply = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playblastOptionBtnApply.sizePolicy().hasHeightForWidth())
        self.playblastOptionBtnApply.setSizePolicy(sizePolicy)
        self.playblastOptionBtnApply.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.playblastOptionBtnApply.setFont(font)
        self.playblastOptionBtnApply.setObjectName("playblastOptionBtnApply")
        self.horizontalLayout.addWidget(self.playblastOptionBtnApply)
        self.pushButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily(u"微软雅黑")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame)
        playblastOptionDialog.setCentralWidget(self.centralwidget)

        self.retranslateUi(playblastOptionDialog)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), playblastOptionDialog.close)
        QtCore.QMetaObject.connectSlotsByName(playblastOptionDialog)

    def retranslateUi(self, playblastOptionDialog):
        playblastOptionDialog.setWindowTitle(QtGui.QApplication.translate("playblastOptionDialog", "拍屏设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("playblastOptionDialog", "动画师名称", None, QtGui.QApplication.UnicodeUTF8))
        self.playblastOptionCBDefault.setText(QtGui.QApplication.translate("playblastOptionDialog", "使用系统默认", None, QtGui.QApplication.UnicodeUTF8))
        self.playblastOptionCBHUD.setText(QtGui.QApplication.translate("playblastOptionDialog", "提高辨识度", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("playblastOptionDialog", "HUD", None, QtGui.QApplication.UnicodeUTF8))
        self.playblastOptionBtnGo.setText(QtGui.QApplication.translate("playblastOptionDialog", "拍屏", None, QtGui.QApplication.UnicodeUTF8))
        self.playblastOptionBtnApply.setText(QtGui.QApplication.translate("playblastOptionDialog", "应用", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("playblastOptionDialog", "关闭", None, QtGui.QApplication.UnicodeUTF8))

